import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const root = process.cwd();
const dataDir = resolve(root, 'docs/data');
const readJson = async (name) => JSON.parse(await readFile(resolve(dataDir, name), 'utf8'));
const bulletLines = (items) => items.map((item) => `- ${item}`);

function renderChangelog(data) {
  const lines = [`# ${data.documentTitle}`, ''];
  for (const paragraph of data.introduction ?? []) lines.push(paragraph, '');
  for (const release of data.releases) {
    lines.push(`## [${release.version}]${release.date ? ` - ${release.date}` : ''}`, '');
    for (const section of release.sections) {
      lines.push(`### ${section.title}`, '', ...section.items.map((item) => `- ${item}`), '');
    }
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

function renderRoadmap(data) {
  const lines = [`# ${data.documentTitle}`, ''];
  for (const block of data.blocks) {
    if (block.type === 'heading') lines.push(`${'#'.repeat(block.level)} ${block.text}`, '');
    else if (block.type === 'paragraph') lines.push(block.text, '');
    else if (block.type === 'bullet') lines.push(`- ${block.text}`);
    else if (block.type === 'task')
      lines.push(`- [${block.status === 'completed' ? 'x' : ' '}] ${block.title}`);
    else if (block.type === 'blank' && lines.at(-1) !== '') lines.push('');
  }
  return `${lines
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd()}\n`;
}

function renderAiContext(project, context, modules, issues, decisions, aiInterface) {
  const activeModules = modules.modules.filter((item) => item.status === 'active');
  const openIssues = issues.issues.filter((item) => item.status !== 'resolved');
  return [
    '# CHB AI Context',
    '',
    '> Generated from `docs/data`. Do not edit this file manually.',
    '',
    '## Start here',
    '',
    '1. Read this file.',
    '2. Read `docs/PROJECT_STATE.json` for machine-readable state.',
    '3. Read relevant decisions and module records before changing architecture.',
    '',
    '## Project',
    '',
    `- ID: \`${project.id}\``,
    `- Name: ${project.name}`,
    `- Current version: \`${context.currentVersion}\``,
    `- Current sprint: \`${context.currentSprint}\``,
    `- Status: ${project.status}`,
    `- Documentation source of truth: \`${project.sourceOfTruth}\``,
    '',
    '## Current goal',
    '',
    context.currentGoal,
    '',
    '## Non-negotiable principles',
    '',
    ...bulletLines(project.principles),
    '',
    '## Active modules',
    '',
    ...activeModules.map((item) => `- \`${item.id}\` — ${item.name}: ${item.description}`),
    '',
    '## Next tasks',
    '',
    ...bulletLines(context.nextTasks),
    '',
    '## Open and accepted issues',
    '',
    ...openIssues.map(
      (item) => `- \`${item.id}\` (${item.severity}, ${item.status}): ${item.description}`
    ),
    '',
    '## Accepted architectural decisions',
    '',
    ...decisions.decisions
      .filter((item) => item.status === 'accepted')
      .map((item) => `- \`${item.id}\`: ${item.title}`),
    '',
    '## Required agent behavior',
    '',
    ...bulletLines(aiInterface.requiredAgentBehavior),
    '',
    '## Canonical machine-readable sources',
    '',
    ...aiInterface.canonicalSources.map((item) => `- \`${item}\``),
    '',
  ].join('\n');
}

function renderAgentFile(title, project, context, aiInterface, extra = []) {
  return [
    `# ${title}`,
    '',
    '> Generated file. Canonical project data lives in `docs/data`.',
    '',
    '## Required reading',
    '',
    '- `docs/AI_CONTEXT.md`',
    '- `docs/PROJECT_STATE.json`',
    '- `docs/AI_PROJECT_INTERFACE.json`',
    '',
    '## Current state',
    '',
    `- Version: \`${context.currentVersion}\``,
    `- Sprint: \`${context.currentSprint}\``,
    '',
    '## Mandatory rules',
    '',
    ...bulletLines(aiInterface.requiredAgentBehavior),
    '',
    '## Project principles',
    '',
    ...bulletLines(project.principles),
    '',
    ...extra,
    '## Verification',
    '',
    '- During development: `npm run format`, `npm run lint`, `npm run build`.',
    '- Before a release commit: `npm run release:prepare`.',
    '',
  ].join('\n');
}

function renderCursorRules(project, context, aiInterface) {
  return [
    '---',
    'description: CHB architecture, documentation and verification rules',
    'alwaysApply: true',
    '---',
    '',
    renderAgentFile('CHB Cursor Project Rules', project, context, aiInterface, [
      '## Cursor workflow',
      '',
      '- Inspect the exact current files before suggesting full-file replacements.',
      '- Keep edits compatible with both Windows 11 and Xubuntu.',
      '- Prefer existing project patterns over introducing new dependencies.',
      '',
    ]),
  ].join('\n');
}

function renderInterfaceDoc(aiInterface) {
  return [
    '# CHB AI Project Interface',
    '',
    'CHB exposes a vendor-neutral project interface generated from structured JSON.',
    '',
    '## Contract',
    '',
    '- Files in `docs/data` are canonical.',
    '- Generated Markdown, manifests and provider adapters are disposable outputs.',
    '- Providers must not create independent project facts in adapter files.',
    '',
    '## Reading order',
    '',
    ...aiInterface.readingOrder.map((item, index) => `${index + 1}. \`${item}\``),
    '',
    '## Generated adapters',
    '',
    ...aiInterface.generatedAdapters.map((item) => `- \`${item.path}\` — ${item.target}`),
    '',
    '## Adding another provider',
    '',
    'Add a generated adapter definition and renderer. Do not duplicate or move canonical data out of `docs/data`.',
    '',
  ].join('\n');
}

function createProjectState(
  project,
  context,
  roadmap,
  features,
  decisions,
  releases,
  modules,
  issues,
  aiInterface
) {
  const tasks = roadmap.blocks.filter((block) => block.type === 'task');
  return {
    interfaceVersion: aiInterface.version,
    generatedFromVersion: context.currentVersion,
    generatedFromSprint: context.currentSprint,
    project,
    context,
    modules: modules.modules,
    issues: issues.issues,
    acceptedDecisions: decisions.decisions.filter((item) => item.status === 'accepted'),
    summary: {
      roadmapTasks: tasks.length,
      completedRoadmapTasks: tasks.filter((item) => item.status === 'completed').length,
      plannedRoadmapTasks: tasks.filter((item) => item.status !== 'completed').length,
      features: features.features.length,
      activeModules: modules.modules.filter((item) => item.status === 'active').length,
      openIssues: issues.issues.filter((item) => item.status !== 'resolved').length,
      acceptedDecisions: decisions.decisions.filter((item) => item.status === 'accepted').length,
      releases: releases.releases.length,
    },
  };
}

async function outputs() {
  const [project, releases, roadmap, features, decisions, context, modules, issues, aiInterface] =
    await Promise.all([
      readJson('project.json'),
      readJson('releases.json'),
      readJson('roadmap.json'),
      readJson('features.json'),
      readJson('decisions.json'),
      readJson('current-context.json'),
      readJson('modules.json'),
      readJson('issues.json'),
      readJson('ai-interface.json'),
    ]);
  const manifest = {
    id: aiInterface.id,
    version: aiInterface.version,
    vendorNeutral: aiInterface.vendorNeutral,
    currentVersion: context.currentVersion,
    currentSprint: context.currentSprint,
    canonicalSources: aiInterface.canonicalSources,
    readingOrder: aiInterface.readingOrder,
    generatedAdapters: aiInterface.generatedAdapters,
    requiredAgentBehavior: aiInterface.requiredAgentBehavior,
  };
  return new Map([
    ['docs/CHANGELOG.md', renderChangelog(releases)],
    ['docs/ROADMAP.md', renderRoadmap(roadmap)],
    [
      'docs/AI_CONTEXT.md',
      renderAiContext(project, context, modules, issues, decisions, aiInterface),
    ],
    [
      'docs/PROJECT_STATE.json',
      `${JSON.stringify(createProjectState(project, context, roadmap, features, decisions, releases, modules, issues, aiInterface), null, 2)}\n`,
    ],
    ['docs/AI_PROJECT_INTERFACE.json', `${JSON.stringify(manifest, null, 2)}\n`],
    ['docs/ai/PROJECT_INTERFACE.md', renderInterfaceDoc(aiInterface)],
    ['AGENTS.md', renderAgentFile('CHB Agent Instructions', project, context, aiInterface)],
    [
      'CLAUDE.md',
      renderAgentFile('CHB Claude Project Instructions', project, context, aiInterface),
    ],
    ['.cursor/rules/chb-project.mdc', renderCursorRules(project, context, aiInterface)],
  ]);
}

const checkMode = process.argv.includes('--check');
let failed = false;
for (const [relativePath, expected] of await outputs()) {
  const absolutePath = resolve(root, relativePath);
  if (checkMode) {
    let current = '';
    try {
      current = await readFile(absolutePath, 'utf8');
    } catch {}
    if (current !== expected) {
      console.error(`OUTDATED: ${relativePath}`);
      failed = true;
    } else console.log(`OK: ${relativePath}`);
  } else {
    await mkdir(dirname(absolutePath), { recursive: true });
    await writeFile(absolutePath, expected, 'utf8');
    console.log(`GENERATED: ${relativePath}`);
  }
}
if (failed) {
  console.error(
    'Generated documentation or AI adapters are not up to date. Run: npm run docs:generate'
  );
  process.exitCode = 1;
}
