import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = process.cwd();
const dataDir = resolve(root, 'docs/data');

async function readJson(name) {
  return JSON.parse(await readFile(resolve(dataDir, name), 'utf8'));
}

function renderChangelog(data) {
  const lines = [`# ${data.documentTitle}`, ''];
  for (const paragraph of data.introduction ?? []) lines.push(paragraph, '');
  for (const release of data.releases) {
    const dateSuffix = release.date ? ` - ${release.date}` : '';
    lines.push(`## [${release.version}]${dateSuffix}`, '');
    for (const section of release.sections) {
      lines.push(`### ${section.title}`, '');
      for (const item of section.items) lines.push(`- ${item}`);
      lines.push('');
    }
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

function renderRoadmap(data) {
  const lines = [`# ${data.documentTitle}`, ''];
  for (const block of data.blocks) {
    if (block.type === 'heading') lines.push(`${'#'.repeat(block.level)} ${block.text}`, '');
    else if (block.type === 'paragraph') lines.push(block.text, '');
    else if (block.type === 'bullet') lines.push(`- ${block.text}`);
    else if (block.type === 'task')
      lines.push(`- [${block.status === 'completed' ? 'x' : ' '}] ${block.title}`);
    else if (block.type === 'blank' && lines.at(-1) !== '') lines.push('');
  }
  return `${lines
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd()}\n`;
}

function renderAiContext(project, context, decisions) {
  const lines = [
    '# CHB AI Context',
    '',
    '> Generated from `docs/data`. Do not edit this file manually.',
    '',
    '## Project',
    '',
    `- ID: \`${project.id}\``,
    `- Name: ${project.name}`,
    `- Current version: \`${context.currentVersion}\``,
    `- Current sprint: \`${context.currentSprint}\``,
    `- Status: ${project.status}`,
    `- Source of truth: \`${project.sourceOfTruth}\``,
    '',
    '## Current goal',
    '',
    context.currentGoal,
    '',
    '## Architecture principles',
    '',
    ...project.principles.map((item) => `- ${item}`),
    '',
    '## Last completed',
    '',
    ...context.lastCompleted.map((item) => `- ${item}`),
    '',
    '## Next tasks',
    '',
    ...context.nextTasks.map((item) => `- ${item}`),
    '',
    '## Known issues',
    '',
    ...context.knownIssues.map(
      (item) => `- \`${item.id}\` (${item.severity}, ${item.status}): ${item.description}`
    ),
    '',
    '## Constraints',
    '',
    ...context.constraints.map((item) => `- ${item}`),
    '',
    '## Accepted decisions',
    '',
    ...decisions.decisions
      .filter((item) => item.status === 'accepted')
      .map((item) => `- \`${item.id}\`: ${item.title}`),
    '',
    '## Machine-readable sources',
    '',
    '- `docs/data/project.json`',
    '- `docs/data/releases.json`',
    '- `docs/data/roadmap.json`',
    '- `docs/data/features.json`',
    '- `docs/data/decisions.json`',
    '- `docs/data/current-context.json`',
    '',
  ];
  return lines.join('\n');
}

function createProjectState(project, context, roadmap, features, decisions, releases) {
  const tasks = roadmap.blocks.filter((block) => block.type === 'task');

  return {
    project,
    context,
    summary: {
      roadmapTasks: tasks.length,
      completedRoadmapTasks: tasks.filter((item) => item.status === 'completed').length,
      plannedRoadmapTasks: tasks.filter((item) => item.status !== 'completed').length,
      features: features.features.length,
      acceptedDecisions: decisions.decisions.filter((item) => item.status === 'accepted').length,
      releases: releases.releases.length,
    },
  };
}

async function outputs() {
  const [project, releases, roadmap, features, decisions, context] = await Promise.all([
    readJson('project.json'),
    readJson('releases.json'),
    readJson('roadmap.json'),
    readJson('features.json'),
    readJson('decisions.json'),
    readJson('current-context.json'),
  ]);
  return new Map([
    ['docs/CHANGELOG.md', renderChangelog(releases)],
    ['docs/ROADMAP.md', renderRoadmap(roadmap)],
    ['docs/AI_CONTEXT.md', renderAiContext(project, context, decisions)],
    [
      'docs/PROJECT_STATE.json',
      `${JSON.stringify(createProjectState(project, context, roadmap, features, decisions, releases), null, 2)}\n`,
    ],
  ]);
}

const checkMode = process.argv.includes('--check');
let failed = false;
for (const [relativePath, expected] of await outputs()) {
  const absolutePath = resolve(root, relativePath);
  if (checkMode) {
    let current = '';
    try {
      current = await readFile(absolutePath, 'utf8');
    } catch {}
    if (current !== expected) {
      console.error(`OUTDATED: ${relativePath}`);
      failed = true;
    } else console.log(`OK: ${relativePath}`);
  } else {
    await writeFile(absolutePath, expected, 'utf8');
    console.log(`GENERATED: ${relativePath}`);
  }
}
if (failed) {
  console.error('Generated documentation is not up to date. Run: npm run docs:generate');
  process.exitCode = 1;
}
